language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-18.0.1

    # The SDK version used to compile your project
    - android-19
before_install:
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - echo $ANDROID_HOME
install: true
script: ant release
